Update authConfig.js
Azure-Samples/ms-identity-javascript-v2 pull request #34
Opened 2022-04-20 13:38 UTC by henrymbuguakiarie

The proposed changes improve the clarity of the configuration for developers using our documentation. This sample code is used in [Tutorial: Sign in users and call the Microsoft Graph API from a JavaScript single-page app (SPA) using auth code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-javascript-auth-code)

2022-04-20 13:39 UTC, henrymbuguakiarie commented
@derisen please review

2022-04-24 18:54 UTC, Karingomrz approved these changes

2022-05-04 16:47 UTC, derisen commented on app/authConfig.js
> +        authority: "Enter_the_Cloud_Instance_Id_Here/Enter_the_Tenant_Info_Here",
```suggestion
        authority: "Enter_the_Cloud_Instance_Id_HereEnter_the_Tenant_Info_Here",
```

@henrymbuguakiarie unfortunatelly we need to omit the slash here, since the Azure portal quickstart template replaces this string automatically with a cloud instance string ending with a trailing slash

2022-05-04 16:48 UTC, derisen requested changes
LGTM, one comment to address

2022-05-04 19:00 UTC, derisen approved these changes

2022-05-05 09:13 UTC, henrymbuguakiarie commented
#sign-off

2022-05-05 13:41 UTC, merged