Updated MSAL
Azure-Samples/ms-identity-javascript-v2 pull request #36
Opened 2022-07-03 05:05 UTC by darrenjrobinson

Updated MSAL to 2.26.0 to enable new MSAL features.

2022-07-04 17:13 UTC, derisen commented on app/index.html
> +    if (typeof Msal === 'undefined') document.write(unescape("%3Cscript src='https://alcdn.msauth.net/browser/2.26.0/js/msal-browser.js' type='text/javascript' crossorigin='anonymous' %3E%3C/script%3
`https://alcdn.msauth.net/` is the same CDN link as above, not a backup. Can we please keep the `alcdn.msftauth.net`?

2022-07-04 17:13 UTC, derisen requested changes
Much appreciated @darrenjrobinson , one comment to address

2022-07-05 01:43 UTC, darrenjrobinson commented
Thanks @derisen 
I've updated the PR with an alternate CDN for updated MSAL version.

2022-07-05 17:37 UTC, derisen approved these changes
LGTM, thanks!

2022-07-05 17:37 UTC, merged